#!/bin/bash

git config --global user.name "Pedro Tarazi"
git config --global user.email "pedrotarazi@gmail.com"
git config --global credential.helper 'cache --timeout=43200'

while :
do
    git add .
    git commit -m "commit Pedro"
    git push origin master
    echo -e "\nFin push\n"
    sleep 600
done
