#!/bin/bash
# echo "____________________________________________________"
parametros="2 0.4 0.8"
if [ -z "$1" ] && [ -z "$2" ] && [ -z "$3" ]
then
 echo "Configuracion Automatica: $parametros"
else
 parametros="$1 $2 $3";
 echo "Configuracion Manual: $parametros"
fi
# echo -n "____________________________________________________"

# Eliminar archivo de profiling anterior
rm -f gmon.out

# Compilar los programas
echo "--- COMPILACION ---"
# gcc -fopenmp -o ./serial/canny ./serial/canny.c -lm -O3
gcc -fopenmp -o ./serial/canny ./serial/canny.c -lm -pg -O3 2> z-errores.txt
gcc -fopenmp -o ./paralelo/cannypa ./paralelo/cannypa.c -lm -O3

# Ejecutar los programas
echo "--- EJECUCION EN SERIE ---"
./serial/canny imagen.pgm $parametros
echo
echo "--- EJECUCION EN PARALELO ---"
./paralelo/cannypa imagen.pgm $parametros

# Comprobar si ambos algoritmos producen exactamente el mismo resultado, observando sus hash
md5sum imagen-serial.pgm
md5sum imagen-paralelo.pgm
shasum imagen-serial.pgm
shasum imagen-paralelo.pgm
# diff -s imagen-serial.pgm imagen-paralelo.pgm

# OPCIONES
#	-pg para crear archivo de profiling y abrir con gprof binario
# -O3 para realizar onrolling durante compilacion
# 2> errores.txt para enviar errores y advertencias a un archivo
